# Application Name
spring.application.name=GreetingApp

# Enable H2 Console (accessible at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.url=jdbc:h2:file:./data/greetingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=him
spring.datasource.password=ans

# Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update